
CREATE TABLE IF NOT EXISTS users(
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT,
 email TEXT UNIQUE,
 password TEXT,
 phone TEXT,
 country TEXT
);

CREATE TABLE IF NOT EXISTS profiles(
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 user_id INTEGER,
 name TEXT,
 avatar TEXT,
 is_kids INTEGER DEFAULT 0,
 FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS content(
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 title TEXT,
 type TEXT,
 year INTEGER,
 duration INTEGER,
 is_premium INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS watchlist(
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 user_id INTEGER,
 content_id INTEGER,
 created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscriptions(
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT,
 price INTEGER,
 devices INTEGER
);
